print('*** Welcome to HKSPACE Inventory Management and Record System 1920S1 *** \n')
print('*** This system is developed by CCIT4020 Class No. CL-09 Group No.92 *** \n')
print('--<Basic function>-- \n')
print('1. Add New Item(s): \n')
print('2. Display Item Record(s): \n')
print('3. Search Item Information: \n')
print('4. Modify Item Record(s): \n')
print('5. Delete Item Record(s): \n')
import addItem
def main():
    num=int(input('What is your option (1-5)?'))
    while True:
        if num==1:
            itemlist=addItem.addItem()
            with open('inventory.txt', 'a') as f:
                for item in itemlist:
                    f.write("%s\n" % item )
                f.write('\n')
                    
            add=input('Do you want to add another item record(y/n):')
            while add=='y':
                anotherlist=addItem.addItem()
                with open('inventory.txt', 'a') as f:
                    for item in anotherlist:
                        f.write("%s\n" % item  )
                    f.write('\n')
                        
                add=input('Do you want to add another item record(y/n):')
                 
            while add=='n':
                f.close()
                break
                
            
  
            
        elif num==2:
            print('Items Infromatiom')
            f= open('inventory.txt', 'r')
            recordnumber = f.readline()

            while recordnumber !='':
                itemname = f.readline()
                itemnumber = f.readline()
                category = f.readline()
                quantity = f.readline()
                weight = f.readline()
                recipient = f.readline()
                finaldestination = f.readline()
                deliverystatus = f.readline()
                NewLine = f.readline()
                print('Record number:',recordnumber,end='')
                print('Item name:',itemname,end='')
                print('Item number:',itemnumber,end='')
                print('Category:',category,end='')
                print('Quantity:',quantity,end='')
                print('Weight:',weight,end='')
                print('Recipient:',recipient,end='')
                print('Final destination:',finaldestination,end='')
                print('Delivery status:',deliverystatus)


                recordnumber = f.readline()
            
            
            
        elif num==3:
            f=open('inventory.txt','r')
            search=int(input('Which item do you want to search?(1-50)'))

            line1=f.readline()
            line2=f.readline()
            line3=f.readline()
            line4=f.readline()
            line5=f.readline()
            line6=f.readline()
            line7=f.readline()
            line8=f.readline()
            line9=f.readline()
            line10=f.readline()
            line11=f.readline()
            line12=f.readline()
            line13=f.readline()
            line14=f.readline()
            line15=f.readline()
            line16=f.readline()
            line17=f.readline()
            line18=f.readline()
            line19=f.readline()
            line20=f.readline()
            line21=f.readline()
            line22=f.readline()
            line23=f.readline()
            line24=f.readline()
            line25=f.readline()
            line26=f.readline()
            line27=f.readline()
            line28=f.readline()
            line29=f.readline()
            line30=f.readline()
            line31=f.readline()
            line32=f.readline()
            line33=f.readline()
            line34=f.readline()
            line35=f.readline()
            line36=f.readline()
            line37=f.readline()
            line38=f.readline()
            line39=f.readline()
            line40=f.readline()
            line41=f.readline()
            line42=f.readline()
            line43=f.readline()
            line44=f.readline()
            line45=f.readline()
            line46=f.readline()
            line47=f.readline()
            line48=f.readline()
            line49=f.readline()
            line50=f.readline()
            line51=f.readline()
            line52=f.readline()
            line53=f.readline()
            line54=f.readline()
            line55=f.readline()
            line56=f.readline()
            line57=f.readline()
            line58=f.readline()
            line59=f.readline()
            line60=f.readline()
            line61=f.readline()
            line62=f.readline()
            line63=f.readline()
            line64=f.readline()
            line65=f.readline()
            line66=f.readline()
            line67=f.readline()
            line68=f.readline()
            line69=f.readline()
            line70=f.readline()
            line71=f.readline()
            line72=f.readline()
            line73=f.readline()
            line74=f.readline()
            line75=f.readline()
            line76=f.readline()
            line77=f.readline()
            line78=f.readline()
            line79=f.readline()
            line80=f.readline()
            line81=f.readline()
            line82=f.readline()
            line83=f.readline()
            line84=f.readline()
            line85=f.readline()
            line86=f.readline()
            line87=f.readline()
            line88=f.readline()
            line89=f.readline()
            line90=f.readline()
            line91=f.readline()
            line92=f.readline()
            line93=f.readline()
            line94=f.readline()
            line95=f.readline()
            line96=f.readline()
            line97=f.readline()
            line98=f.readline()
            line99=f.readline()
            line100=f.readline()
            line101=f.readline()
            line102=f.readline()
            line103=f.readline()
            line104=f.readline()
            line105=f.readline()
            line106=f.readline()
            line107=f.readline()
            line108=f.readline()
            line109=f.readline()
            line110=f.readline()
            line111=f.readline()
            line112=f.readline()
            line113=f.readline()
            line114=f.readline()
            line115=f.readline()
            line116=f.readline()
            line117=f.readline()
            line118=f.readline()
            line119=f.readline()
            line120=f.readline()
            line121=f.readline()
            line122=f.readline()
            line123=f.readline()
            line124=f.readline()
            line125=f.readline()
            line126=f.readline()
            line127=f.readline()
            line128=f.readline()
            line129=f.readline()
            line130=f.readline()
            line131=f.readline()
            line132=f.readline()
            line133=f.readline()
            line134=f.readline()
            line135=f.readline()
            line136=f.readline()
            line137=f.readline()
            line138=f.readline()
            line139=f.readline()
            line140=f.readline()
            line141=f.readline()
            line142=f.readline()
            line143=f.readline()
            line144=f.readline()
            line145=f.readline()
            line146=f.readline()
            line147=f.readline()
            line148=f.readline()
            line149=f.readline()
            line150=f.readline()
            line151=f.readline()
            line152=f.readline()
            line153=f.readline()
            line154=f.readline()
            line155=f.readline()
            line156=f.readline()
            line157=f.readline()
            line158=f.readline()
            line159=f.readline()
            line160=f.readline()
            line161=f.readline()
            line162=f.readline()
            line163=f.readline()
            line164=f.readline()
            line165=f.readline()
            line166=f.readline()
            line167=f.readline()
            line168=f.readline()
            line169=f.readline()
            line170=f.readline()
            line171=f.readline()
            line172=f.readline()
            line173=f.readline()
            line174=f.readline()
            line175=f.readline()
            line176=f.readline()
            line177=f.readline()
            line178=f.readline()
            line179=f.readline()
            line180=f.readline()
            line181=f.readline()
            line182=f.readline()
            line183=f.readline()
            line184=f.readline()
            line185=f.readline()
            line186=f.readline()
            line187=f.readline()
            line188=f.readline()
            line189=f.readline()
            line190=f.readline()
            line191=f.readline()
            line192=f.readline()
            line193=f.readline()
            line194=f.readline()
            line195=f.readline()
            line196=f.readline()
            line197=f.readline()
            line198=f.readline()
            line199=f.readline()
            line200=f.readline()
            line201=f.readline()
            line202=f.readline()
            line203=f.readline()
            line204=f.readline()
            line205=f.readline()
            line206=f.readline()
            line207=f.readline()
            line208=f.readline()
            line209=f.readline()
            line210=f.readline()
            line211=f.readline()
            line212=f.readline()
            line213=f.readline()
            line214=f.readline()
            line215=f.readline()
            line216=f.readline()
            line217=f.readline()
            line218=f.readline()
            line219=f.readline()
            line220=f.readline()
            line221=f.readline()
            line222=f.readline()
            line223=f.readline()
            line224=f.readline()
            line225=f.readline()
            line226=f.readline()
            line227=f.readline()
            line228=f.readline()
            line229=f.readline()
            line230=f.readline()
            line231=f.readline()
            line232=f.readline()
            line233=f.readline()
            line234=f.readline()
            line235=f.readline()
            line236=f.readline()
            line237=f.readline()
            line238=f.readline()
            line239=f.readline()
            line240=f.readline()
            line241=f.readline()
            line242=f.readline()
            line243=f.readline()
            line244=f.readline()
            line245=f.readline()
            line246=f.readline()
            line247=f.readline()
            line248=f.readline()
            line249=f.readline()
            line250=f.readline()
            line251=f.readline()
            line252=f.readline()
            line253=f.readline()
            line254=f.readline()
            line255=f.readline()
            line256=f.readline()
            line257=f.readline()
            line258=f.readline()
            line259=f.readline()
            line260=f.readline()
            line261=f.readline()
            line262=f.readline()
            line263=f.readline()
            line264=f.readline()
            line265=f.readline()
            line266=f.readline()
            line267=f.readline()
            line268=f.readline()
            line269=f.readline()
            line270=f.readline()
            line271=f.readline()
            line272=f.readline()
            line273=f.readline()
            line274=f.readline()
            line275=f.readline()
            line276=f.readline()
            line277=f.readline()
            line278=f.readline()
            line279=f.readline()
            line280=f.readline()
            line281=f.readline()
            line282=f.readline()
            line283=f.readline()
            line284=f.readline()
            line285=f.readline()
            line286=f.readline()
            line287=f.readline()
            line288=f.readline()
            line289=f.readline()
            line290=f.readline()
            line291=f.readline()
            line292=f.readline()
            line293=f.readline()
            line294=f.readline()
            line295=f.readline()
            line296=f.readline()
            line297=f.readline()
            line298=f.readline()
            line299=f.readline()
            line300=f.readline()
            line301=f.readline()
            line302=f.readline()
            line303=f.readline()
            line304=f.readline()
            line305=f.readline()
            line306=f.readline()
            line307=f.readline()
            line308=f.readline()
            line309=f.readline()
            line310=f.readline()
            line311=f.readline()
            line312=f.readline()
            line313=f.readline()
            line314=f.readline()
            line315=f.readline()
            line316=f.readline()
            line317=f.readline()
            line318=f.readline()
            line319=f.readline()
            line320=f.readline()
            line321=f.readline()
            line322=f.readline()
            line323=f.readline()
            line324=f.readline()
            line325=f.readline()
            line326=f.readline()
            line327=f.readline()
            line328=f.readline()
            line329=f.readline()
            line330=f.readline()
            line331=f.readline()
            line332=f.readline()
            line333=f.readline()
            line334=f.readline()
            line335=f.readline()
            line336=f.readline()
            line337=f.readline()
            line338=f.readline()
            line339=f.readline()
            line340=f.readline()
            line341=f.readline()
            line342=f.readline()
            line343=f.readline()
            line344=f.readline()
            line345=f.readline()
            line346=f.readline()
            line347=f.readline()
            line348=f.readline()
            line349=f.readline()
            line350=f.readline()
            line351=f.readline()
            line352=f.readline()
            line353=f.readline()
            line354=f.readline()
            line355=f.readline()
            line356=f.readline()
            line357=f.readline()
            line358=f.readline()
            line359=f.readline()
            line360=f.readline()
            line361=f.readline()
            line362=f.readline()
            line363=f.readline()
            line364=f.readline()
            line365=f.readline()
            line366=f.readline()
            line367=f.readline()
            line368=f.readline()
            line369=f.readline()
            line370=f.readline()
            line371=f.readline()
            line372=f.readline()
            line373=f.readline()
            line374=f.readline()
            line375=f.readline()
            line376=f.readline()
            line377=f.readline()
            line378=f.readline()
            line379=f.readline()
            line380=f.readline()
            line381=f.readline()
            line382=f.readline()
            line383=f.readline()
            line384=f.readline()
            line385=f.readline()
            line386=f.readline()
            line387=f.readline()
            line388=f.readline()
            line389=f.readline()
            line390=f.readline()
            line391=f.readline()
            line392=f.readline()
            line393=f.readline()
            line394=f.readline()
            line395=f.readline()
            line396=f.readline()
            line397=f.readline()
            line398=f.readline()
            line399=f.readline()
            line400=f.readline()
            line401=f.readline()
            line402=f.readline()
            line403=f.readline()
            line404=f.readline()
            line405=f.readline()
            line406=f.readline()
            line407=f.readline()
            line408=f.readline()
            line409=f.readline()
            line410=f.readline()
            line411=f.readline()
            line412=f.readline()
            line413=f.readline()
            line414=f.readline()
            line415=f.readline()
            line416=f.readline()
            line417=f.readline()
            line418=f.readline()
            line419=f.readline()
            line420=f.readline()
            line421=f.readline()
            line422=f.readline()
            line423=f.readline()
            line424=f.readline()
            line425=f.readline()
            line426=f.readline()
            line427=f.readline()
            line428=f.readline()
            line429=f.readline()
            line430=f.readline()
            line431=f.readline()
            line432=f.readline()
            line433=f.readline()
            line434=f.readline()
            line435=f.readline()
            line436=f.readline()
            line437=f.readline()
            line438=f.readline()
            line439=f.readline()
            line440=f.readline()
            line441=f.readline()
            line442=f.readline()
            line443=f.readline()
            line444=f.readline()
            line445=f.readline()
            line446=f.readline()
            line447=f.readline()
            line448=f.readline()
            line449=f.readline()
            line450=f.readline()
            line451=f.readline()
            line452=f.readline()
            line453=f.readline()
            line454=f.readline()
            line455=f.readline()
            line456=f.readline()
            line457=f.readline()
            line458=f.readline()
            line459=f.readline()
            line460=f.readline()
            line461=f.readline()
            line462=f.readline()
            line463=f.readline()
            line464=f.readline()
            line465=f.readline()
            line466=f.readline()
            line467=f.readline()
            line468=f.readline()
            line469=f.readline()
            line470=f.readline()
            line471=f.readline()
            line472=f.readline()
            line473=f.readline()
            line474=f.readline()
            line475=f.readline()
            line476=f.readline()
            line477=f.readline()
            line478=f.readline()
            line479=f.readline()
            line480=f.readline()
            line481=f.readline()
            line482=f.readline()
            line483=f.readline()
            line484=f.readline()
            line485=f.readline()
            line486=f.readline()
            line487=f.readline()
            line488=f.readline()
            line489=f.readline()
            line490=f.readline()
            line491=f.readline()
            line492=f.readline()
            line493=f.readline()
            line494=f.readline()
            line495=f.readline()
            line496=f.readline()
            line497=f.readline()
            line498=f.readline()
            line499=f.readline()

            if search==1:
                print(line1)
                print(line2)
                print(line3)
                print(line4)
                print(line5)
                print(line6)
                print(line7)
                print(line8)
                print(line9)
                print(line10)

            elif search==2:
                print(line11)
                print(line12)
                print(line13)
                print(line14)
                print(line15)
                print(line16)
                print(line17)
                print(line18)
                print(line19)

            elif search==3:
                print(line21)
                print(line22)
                print(line23)
                print(line24)
                print(line25)
                print(line26)
                print(line27)
                print(line28)
                print(line29)

            elif search==4:
                print(line31)
                print(line32)
                print(line33)
                print(line34)
                print(line35)
                print(line36)
                print(line37)
                print(line38)
                print(line39)
            elif search==5:
                print(line41)
                print(line42)
                print(line43)
                print(line44)
                print(line45)
                print(line46)
                print(line47)
                print(line48)
                print(line49)
            elif search==6:
                print(line51)
                print(line52)
                print(line53)
                print(line54)
                print(line55)
                print(line56)
                print(line57)
                print(line58)
                print(line59)
            elif search==7:
                print(line61)
                print(line62)
                print(line63)
                print(line64)
                print(line65)
                print(line66)
                print(line67)
                print(line68)
                print(line69)
            elif search==8:
                print(line71)
                print(line72)
                print(line73)
                print(line74)
                print(line75)
                print(line76)
                print(line77)
                print(line78)
                print(line79)
            elif search==9:
                print(line81)
                print(line82)
                print(line83)
                print(line84)
                print(line85)
                print(line86)
                print(line87)
                print(line88)
                print(line89)
            elif search==10:
                print(line91)
                print(line92)
                print(line93)
                print(line94)
                print(line95)
                print(line96)
                print(line97)
                print(line98)
                print(line99)
            elif search==11:
                print(line101)
                print(line102)
                print(line103)
                print(line104)
                print(line105)
                print(line106)
                print(line107)
                print(line108)
                print(line109)
            elif search==12:
                print(line111)
                print(line112)
                print(line113)
                print(line114)
                print(line115)
                print(line116)
                print(line117)
                print(line118)
                print(line119)
            elif search==13:
                print(line121)
                print(line122)
                print(line123)
                print(line124)
                print(line125)
                print(line126)
                print(line127)
                print(line128)
                print(line129)
            elif search==14:
                print(line131)
                print(line132)
                print(line133)
                print(line134)
                print(line135)
                print(line136)
                print(line137)
                print(line138)
                print(line139)
            elif search==15:
                print(line141)
                print(line142)
                print(line143)
                print(line144)
                print(line145)
                print(line146)
                print(line147)
                print(line148)
                print(line149)
            elif search==16:
                print(line151)
                print(line152)
                print(line153)
                print(line154)
                print(line155)
                print(line156)
                print(line157)
                print(line158)
                print(line159)
            elif search==17:
                print(line161)
                print(line162)
                print(line163)
                print(line164)
                print(line165)
                print(line166)
                print(line167)
                print(line168)
                print(line169)
            elif search==18:
                print(line171)
                print(line172)
                print(line173)
                print(line174)
                print(line175)
                print(line176)
                print(line177)
                print(line178)
                print(line179)
            elif search==19:
                print(line181)
                print(line182)
                print(line183)
                print(line184)
                print(line185)
                print(line186)
                print(line187)
                print(line188)
                print(line189)
            elif search==20:
                print(line191)
                print(line192)
                print(line193)
                print(line194)
                print(line195)
                print(line196)
                print(line197)
                print(line198)
                print(line199)
            elif search==21:
                print(line201)
                print(line202)
                print(line203)
                print(line204)
                print(line205)
                print(line206)
                print(line207)
                print(line208)
                print(line209)
            elif search==22:
                print(line211)
                print(line212)
                print(line213)
                print(line214)
                print(line215)
                print(line216)
                print(line217)
                print(line218)
                print(line219)
            elif search==23:
                print(line221)
                print(line222)
                print(line223)
                print(line224)
                print(line225)
                print(line226)
                print(line227)
                print(line228)
                print(line229)
            elif search==24:
                print(line231)
                print(line232)
                print(line233)
                print(line234)
                print(line235)
                print(line236)
                print(line237)
                print(line238)
                print(line239)
            elif search==25:
                print(line241)
                print(line242)
                print(line243)
                print(line244)
                print(line245)
                print(line246)
                print(line247)
                print(line248)
                print(line249)
            elif search==26:
                print(line251)
                print(line252)
                print(line253)
                print(line254)
                print(line255)
                print(line256)
                print(line257)
                print(line258)
                print(line259)
            elif search==27:
                print(line261)
                print(line262)
                print(line263)
                print(line264)
                print(line265)
                print(line266)
                print(line267)
                print(line268)
                print(line269)
            elif search==28:
                print(line271)
                print(line272)
                print(line273)
                print(line274)
                print(line275)
                print(line276)
                print(line277)
                print(line278)
                print(line279)
            elif search==29:
                print(line281)
                print(line282)
                print(line283)
                print(line284)
                print(line285)
                print(line286)
                print(line287)
                print(line288)
                print(line289)
            elif search==30:
                print(line291)
                print(line292)
                print(line293)
                print(line294)
                print(line295)
                print(line296)
                print(line297)
                print(line298)
                print(line299)
            elif search==31:
                print(line301)
                print(line302)
                print(line303)
                print(line304)
                print(line305)
                print(line306)
                print(line307)
                print(line308)
                print(line309)
            elif search==32:
                print(line311)
                print(line312)
                print(line313)
                print(line314)
                print(line315)
                print(line316)
                print(line317)
                print(line318)
                print(line319)
            elif search==33:
                print(line321)
                print(line322)
                print(line323)
                print(line324)
                print(line325)
                print(line326)
                print(line327)
                print(line328)
                print(line329)
            elif search==34:
                print(line331)
                print(line332)
                print(line333)
                print(line334)
                print(line335)
                print(line336)
                print(line337)
                print(line338)
                print(line339)
            elif search==35:
                print(line341)
                print(line342)
                print(line343)
                print(line344)
                print(line345)
                print(line346)
                print(line347)
                print(line348)
                print(line349)
            elif search==36:
                print(line351)
                print(line352)
                print(line353)
                print(line354)
                print(line355)
                print(line356)
                print(line357)
                print(line358)
                print(line359)
            elif search==37:
                print(line361)
                print(line362)
                print(line363)
                print(line364)
                print(line365)
                print(line366)
                print(line367)
                print(line368)
                print(line369)
            elif search==38:
                print(line371)
                print(line372)
                print(line373)
                print(line374)
                print(line375)
                print(line376)
                print(line377)
                print(line378)
                print(line379)
            elif search==39:
                print(line381)
                print(line382)
                print(line383)
                print(line384)
                print(line385)
                print(line386)
                print(line387)
                print(line388)
                print(line389)
            elif search==40:
                print(line391)
                print(line392)
                print(line393)
                print(line394)
                print(line395)
                print(line396)
                print(line397)
                print(line398)
                print(line399)
            elif search==41:
                print(line401)
                print(line402)
                print(line403)
                print(line404)
                print(line405)
                print(line406)
                print(line407)
                print(line408)
                print(line409)
            elif search==42:
                print(line411)
                print(line412)
                print(line413)
                print(line414)
                print(line415)
                print(line416)
                print(line417)
                print(line418)
                print(line419)
            elif search==43:
                print(line421)
                print(line422)
                print(line423)
                print(line424)
                print(line425)
                print(line426)
                print(line427)
                print(line428)
                print(line429)
            elif search==44:
                print(line431)
                print(line432)
                print(line433)
                print(line434)
                print(line435)
                print(line436)
                print(line437)
                print(line438)
                print(line439)
            elif search==45:
                print(line441)
                print(line442)
                print(line443)
                print(line444)
                print(line445)
                print(line446)
                print(line447)
                print(line448)
                print(line449)
            elif search==46:
                print(line451)
                print(line452)
                print(line453)
                print(line454)
                print(line455)
                print(line456)
                print(line457)
                print(line458)
                print(line459)
            elif search==47:
                print(line461)
                print(line462)
                print(line463)
                print(line464)
                print(line465)
                print(line466)
                print(line467)
                print(line468)
                print(line469)
            elif search==48:
                print(line471)
                print(line472)
                print(line473)
                print(line474)
                print(line475)
                print(line476)
                print(line477)
                print(line478)
                print(line479)
            elif search==49:
                print(line481)
                print(line482)
                print(line483)
                print(line484)
                print(line485)
                print(line486)
                print(line487)
                print(line488)
                print(line489)
            elif search==50:
                print(line491)
                print(line492)
                print(line493)
                print(line494)
                print(line495)
                print(line496)
                print(line497)
                print(line498)
                print(line499)

            other=str(input('Do you want to read another item record?(yes/no)'))

            while other=='yes':
                search=int(input('Which item do you want to search?(1-50)'))
                

                if search==1:
                    print(line1)
                    print(line2)
                    print(line3)
                    print(line4)
                    print(line5)
                    print(line6)
                    print(line7)
                    print(line8)
                    print(line9)
                    print(line10)

                elif search==2:
                    print(line11)
                    print(line12)
                    print(line13)
                    print(line14)
                    print(line15)
                    print(line16)
                    print(line17)
                    print(line18)
                    print(line19)

                elif search==3:
                    print(line21)
                    print(line22)
                    print(line23)
                    print(line24)
                    print(line25)
                    print(line26)
                    print(line27)
                    print(line28)
                    print(line29)

                elif search==4:
                    print(line31)
                    print(line32)
                    print(line33)
                    print(line34)
                    print(line35)
                    print(line36)
                    print(line37)
                    print(line38)
                    print(line39)
                elif search==5:
                    print(line41)
                    print(line42)
                    print(line43)
                    print(line44)
                    print(line45)
                    print(line46)
                    print(line47)
                    print(line48)
                    print(line49)
                elif search==6:
                    print(line51)
                    print(line52)
                    print(line53)
                    print(line54)
                    print(line55)
                    print(line56)
                    print(line57)
                    print(line58)
                    print(line59)
                elif search==7:
                    print(line61)
                    print(line62)
                    print(line63)
                    print(line64)
                    print(line65)
                    print(line66)
                    print(line67)
                    print(line68)
                    print(line69)
                elif search==8:
                    print(line71)
                    print(line72)
                    print(line73)
                    print(line74)
                    print(line75)
                    print(line76)
                    print(line77)
                    print(line78)
                    print(line79)
                elif search==9:
                    print(line81)
                    print(line82)
                    print(line83)
                    print(line84)
                    print(line85)
                    print(line86)
                    print(line87)
                    print(line88)
                    print(line89)
                elif search==10:
                    print(line91)
                    print(line92)
                    print(line93)
                    print(line94)
                    print(line95)
                    print(line96)
                    print(line97)
                    print(line98)
                    print(line99)
                elif search==11:
                    print(line101)
                    print(line102)
                    print(line103)
                    print(line104)
                    print(line105)
                    print(line106)
                    print(line107)
                    print(line108)
                    print(line109)
                elif search==12:
                    print(line111)
                    print(line112)
                    print(line113)
                    print(line114)
                    print(line115)
                    print(line116)
                    print(line117)
                    print(line118)
                    print(line119)
                elif search==13:
                    print(line121)
                    print(line122)
                    print(line123)
                    print(line124)
                    print(line125)
                    print(line126)
                    print(line127)
                    print(line128)
                    print(line129)
                elif search==14:
                    print(line131)
                    print(line132)
                    print(line133)
                    print(line134)
                    print(line135)
                    print(line136)
                    print(line137)
                    print(line138)
                    print(line139)
                elif search==15:
                    print(line141)
                    print(line142)
                    print(line143)
                    print(line144)
                    print(line145)
                    print(line146)
                    print(line147)
                    print(line148)
                    print(line149)
                elif search==16:
                    print(line151)
                    print(line152)
                    print(line153)
                    print(line154)
                    print(line155)
                    print(line156)
                    print(line157)
                    print(line158)
                    print(line159)
                elif search==17:
                    print(line161)
                    print(line162)
                    print(line163)
                    print(line164)
                    print(line165)
                    print(line166)
                    print(line167)
                    print(line168)
                    print(line169)
                elif search==18:
                    print(line171)
                    print(line172)
                    print(line173)
                    print(line174)
                    print(line175)
                    print(line176)
                    print(line177)
                    print(line178)
                    print(line179)
                elif search==19:
                    print(line181)
                    print(line182)
                    print(line183)
                    print(line184)
                    print(line185)
                    print(line186)
                    print(line187)
                    print(line188)
                    print(line189)
                elif search==20:
                    print(line191)
                    print(line192)
                    print(line193)
                    print(line194)
                    print(line195)
                    print(line196)
                    print(line197)
                    print(line198)
                    print(line199)
                elif search==21:
                    print(line201)
                    print(line202)
                    print(line203)
                    print(line204)
                    print(line205)
                    print(line206)
                    print(line207)
                    print(line208)
                    print(line209)
                elif search==22:
                    print(line211)
                    print(line212)
                    print(line213)
                    print(line214)
                    print(line215)
                    print(line216)
                    print(line217)
                    print(line218)
                    print(line219)
                elif search==23:
                    print(line221)
                    print(line222)
                    print(line223)
                    print(line224)
                    print(line225)
                    print(line226)
                    print(line227)
                    print(line228)
                    print(line229)
                elif search==24:
                    print(line231)
                    print(line232)
                    print(line233)
                    print(line234)
                    print(line235)
                    print(line236)
                    print(line237)
                    print(line238)
                    print(line239)
                elif search==25:
                    print(line241)
                    print(line242)
                    print(line243)
                    print(line244)
                    print(line245)
                    print(line246)
                    print(line247)
                    print(line248)
                    print(line249)
                elif search==26:
                    print(line251)
                    print(line252)
                    print(line253)
                    print(line254)
                    print(line255)
                    print(line256)
                    print(line257)
                    print(line258)
                    print(line259)
                elif search==27:
                    print(line261)
                    print(line262)
                    print(line263)
                    print(line264)
                    print(line265)
                    print(line266)
                    print(line267)
                    print(line268)
                    print(line269)
                elif search==28:
                    print(line271)
                    print(line272)
                    print(line273)
                    print(line274)
                    print(line275)
                    print(line276)
                    print(line277)
                    print(line278)
                    print(line279)
                elif search==29:
                    print(line281)
                    print(line282)
                    print(line283)
                    print(line284)
                    print(line285)
                    print(line286)
                    print(line287)
                    print(line288)
                    print(line289)
                elif search==30:
                    print(line291)
                    print(line292)
                    print(line293)
                    print(line294)
                    print(line295)
                    print(line296)
                    print(line297)
                    print(line298)
                    print(line299)
                elif search==31:
                    print(line301)
                    print(line302)
                    print(line303)
                    print(line304)
                    print(line305)
                    print(line306)
                    print(line307)
                    print(line308)
                    print(line309)
                elif search==32:
                    print(line311)
                    print(line312)
                    print(line313)
                    print(line314)
                    print(line315)
                    print(line316)
                    print(line317)
                    print(line318)
                    print(line319)
                elif search==33:
                    print(line321)
                    print(line322)
                    print(line323)
                    print(line324)
                    print(line325)
                    print(line326)
                    print(line327)
                    print(line328)
                    print(line329)
                elif search==34:
                    print(line331)
                    print(line332)
                    print(line333)
                    print(line334)
                    print(line335)
                    print(line336)
                    print(line337)
                    print(line338)
                    print(line339)
                elif search==35:
                    print(line341)
                    print(line342)
                    print(line343)
                    print(line344)
                    print(line345)
                    print(line346)
                    print(line347)
                    print(line348)
                    print(line349)
                elif search==36:
                    print(line351)
                    print(line352)
                    print(line353)
                    print(line354)
                    print(line355)
                    print(line356)
                    print(line357)
                    print(line358)
                    print(line359)
                elif search==37:
                    print(line361)
                    print(line362)
                    print(line363)
                    print(line364)
                    print(line365)
                    print(line366)
                    print(line367)
                    print(line368)
                    print(line369)
                elif search==38:
                    print(line371)
                    print(line372)
                    print(line373)
                    print(line374)
                    print(line375)
                    print(line376)
                    print(line377)
                    print(line378)
                    print(line379)
                elif search==39:
                    print(line381)
                    print(line382)
                    print(line383)
                    print(line384)
                    print(line385)
                    print(line386)
                    print(line387)
                    print(line388)
                    print(line389)
                elif search==40:
                    print(line391)
                    print(line392)
                    print(line393)
                    print(line394)
                    print(line395)
                    print(line396)
                    print(line397)
                    print(line398)
                    print(line399)
                elif search==41:
                    print(line401)
                    print(line402)
                    print(line403)
                    print(line404)
                    print(line405)
                    print(line406)
                    print(line407)
                    print(line408)
                    print(line409)
                elif search==42:
                    print(line411)
                    print(line412)
                    print(line413)
                    print(line414)
                    print(line415)
                    print(line416)
                    print(line417)
                    print(line418)
                    print(line419)
                elif search==43:
                    print(line421)
                    print(line422)
                    print(line423)
                    print(line424)
                    print(line425)
                    print(line426)
                    print(line427)
                    print(line428)
                    print(line429)
                elif search==44:
                    print(line431)
                    print(line432)
                    print(line433)
                    print(line434)
                    print(line435)
                    print(line436)
                    print(line437)
                    print(line438)
                    print(line439)
                elif search==45:
                    print(line441)
                    print(line442)
                    print(line443)
                    print(line444)
                    print(line445)
                    print(line446)
                    print(line447)
                    print(line448)
                    print(line449)
                elif search==46:
                    print(line451)
                    print(line452)
                    print(line453)
                    print(line454)
                    print(line455)
                    print(line456)
                    print(line457)
                    print(line458)
                    print(line459)
                elif search==47:
                    print(line461)
                    print(line462)
                    print(line463)
                    print(line464)
                    print(line465)
                    print(line466)
                    print(line467)
                    print(line468)
                    print(line469)
                elif search==48:
                    print(line471)
                    print(line472)
                    print(line473)
                    print(line474)
                    print(line475)
                    print(line476)
                    print(line477)
                    print(line478)
                    print(line479)
                elif search==49:
                    print(line481)
                    print(line482)
                    print(line483)
                    print(line484)
                    print(line485)
                    print(line486)
                    print(line487)
                    print(line488)
                    print(line489)
                elif search==50:
                    print(line491)
                    print(line492)
                    print(line493)
                    print(line494)
                    print(line495)
                    print(line496)
                    print(line497)
                    print(line498)
                    print(line499)
                other=str(input('Do you want to read another item record?(yes/no)'))
            while other=='no':
                f.close()
                break

            
            

        elif num==4:
            f = open ("inventory.txt","w")
            index=int(input('What record number do you want to modify?'))
            item=(input("What do you want to add?"))

            f.write(str(index)+"\n")
            f.write(item+"\n")

            edit=input("Do you want to modify another item record? (yes/no)")
            while edit == "yes":
                    index=int(input('What record number do you want to modify?'))
                    item=(input("What do you want to add?"))

                    f.write(str(index)+"\n")
                    f.write(item+"\n")

                    edit=input("Do you want to modify another item record? (yes/no)")

                    
            while edit == "no":
                    f.close()
                    print('Updated inventory list.') 
                    break
                        


        elif num==5:
            delete = str(input('Do you want to delete item record? (yes/no) '))
            while delete == "yes":
                with open('inventory.txt', 'r') as f:
                    initial_lines = f.readlines()
                    to_delete = input('What record do you want to delete? ').strip()
                with open('inventory.txt', 'w') as f:
                    deleting = 0
                    for line in initial_lines:
                        if line.strip('\n') == to_delete:
                            deleting = 1
                            counter = 0
                        if deleting:
                            counter += 1
                            if counter == 10:
                                deleting = 0
                        else:
                            f.write(line)
                    print('\nUpdated inventory list.\n')
                    delete = str(input('Do you want to delete another item record? (yes/no) '))


        break


main()

